version: "3"

services:
  wekandb:
    image: mongo:latest
    container_name: wekan-db
    restart: always
    command: mongod --oplogSize 128
    networks:
      - wekan-tier
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump
  wekan:
    image: quay.io/wekan/wekan
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
      - drop
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=https://${HOST}
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - SCROLLINERTIA=0
      - SCROLLAMOUNT=auto
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - wekandb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wekan.rule=Host(`${HOST}`)"
      - "traefik.http.routers.wekan.entrypoints=websecure"
      - "traefik.http.routers.wekan.tls.certresolver=doresolver"
      - "traefik.http.services.wekan.loadbalancer.server.port=8080"
      # https redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"

volumes:
  wekan-db:
  wekan-db-dump:

networks:
  wekan-tier:
    driver: bridge
  drop:
    external: true
